In [1]:
import pandas as pd

In [2]:
df = pd.read_excel('sales.xlsx')
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country,City,State,Postal Code,Region,Product ID,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-08-11 00:00:00,2016-11-11 00:00:00,Second Class,CG-12520,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-08-11 00:00:00,2016-11-11 00:00:00,Second Class,CG-12520,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-12-06 00:00:00,6/16/2016,Second Class,DV-13045,United States,Los Angeles,California,90036,West,OFF-LA-10000240,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-11-10 00:00:00,10/18/2015,Standard Class,SO-20335,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-11-10 00:00:00,10/18/2015,Standard Class,SO-20335,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,1/21/2014,1/23/2014,Second Class,TB-21400,United States,Miami,Florida,33180,South,FUR-FU-10001889,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,2/26/2017,2017-03-03 00:00:00,Standard Class,DB-13060,United States,Costa Mesa,California,92627,West,FUR-FU-10000747,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,2/26/2017,2017-03-03 00:00:00,Standard Class,DB-13060,United States,Costa Mesa,California,92627,West,TEC-PH-10003645,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,2/26/2017,2017-03-03 00:00:00,Standard Class,DB-13060,United States,Costa Mesa,California,92627,West,OFF-PA-10004041,29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,2017-04-05 00:00:00,2017-09-05 00:00:00,Second Class,CC-12220,United States,Westminster,California,92683,West,OFF-AP-10002684,243.1600,2,0.00,72.9480

In [7]:
from pyspark.sql import SparkSession

In [10]:
spark = SparkSession.builder.appName('Sales-ETL').getOrCreate()
# Load the dataset
data_path = "/sales.xlsx"  # Adjust this path to your dataset
sales_df = spark.read.excel(data_path, header=True, inferSchema=True)

# Show the dataset
sales_df.show()

PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.